"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NETWORK_CONSTANTS = exports.VALIDATION_CONSTANTS = exports.CACHE_CONSTANTS = exports.RATE_LIMIT_CONSTANTS = exports.AI_CONSTANTS = exports.TIME_CONSTANTS = void 0;
exports.TIME_CONSTANTS = {
    ONE_MINUTE: 60 * 1000,
    ONE_HOUR: 60 * 60 * 1000,
    ONE_DAY: 24 * 60 * 60 * 1000,
    TEN_SECONDS: 10 * 1000,
    FIVE_MINUTES: 5 * 60 * 1000,
};
exports.AI_CONSTANTS = {
    DEFAULT_MAX_TOKENS: 1000,
    DEFAULT_TEMPERATURE: 0.7,
    DEFAULT_MAX_INSIGHT_LENGTH: 500,
    DEFAULT_CONFIDENCE_THRESHOLD: 1,
    OLLAMA_DEFAULT_PORT: 11434,
    OLLAMA_DEFAULT_MODEL: 'llama3.2:3b',
    OPENAI_DEFAULT_MODEL: 'gpt-3.5-turbo',
    CLAUDE_DEFAULT_MODEL: 'claude-3-haiku-20240307',
};
exports.RATE_LIMIT_CONSTANTS = {
    DEFAULT_MAX_REQUESTS_PER_MINUTE: 60,
    DEFAULT_MAX_REQUESTS_PER_HOUR: 1000,
};
exports.CACHE_CONSTANTS = {
    DEFAULT_MAX_SIZE: 1000,
    DEFAULT_TTL: exports.TIME_CONSTANTS.ONE_HOUR,
    MIN_CACHE_SIZE: 100,
    MAX_CACHE_SIZE: 10000,
    LOW_UTILIZATION_THRESHOLD: 0.3,
    CACHE_SHRINK_FACTOR: 0.8,
    HIGH_EVICTION_THRESHOLD: 0.1,
    CACHE_GROW_FACTOR: 1.2,
};
exports.VALIDATION_CONSTANTS = {
    MAX_CONFIG_FILE_SIZE: 100000,
    MAX_TIMEOUT: 300000,
};
exports.NETWORK_CONSTANTS = {
    OLLAMA_DEFAULT_BASE_URL: 'http://localhost:11434',
};
