name: Nightly

permissions:
  contents: read

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: tools-versions.json

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Quality, tests and build
        run: |
          pnpm biome:fix-and-check || true
          pnpm type-check
          pnpm test
          pnpm build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
